export const closet =[
  {
    id: 1,
    title: "hm_jacket_white",
    category: "jacket",
    colour: "white",
    size: "XL",
    length: "long",
    img: "./images/jackets/hm_jacket_white.png",
  },
  {
    id: 2,
    title: "kamuy_vintage_jacket_black",
    category: "jacket",
    colour: "black",
    size: "XL",
    length: "long",
    img: "./images/jackets/kamuy_vintage_jacket_black.png",
  },
  {
    id: 3,
    title: "alfred_coat_black",
    category: "jacket",
    colour: "black",
    size: "XL",
    length: "long",
    img: "./images/jackets/alfred_coat_black.png",
  },
  {
    id: 4,
    title: "fountain_tire_jacket_green",
    category: "jacket",
    colour: "green",
    size: "XL",
    length: "long",
    img: "./images/jackets/fountain_tire_jacket_green.png",
  },
  {
    id: 5,
    title: "hm_sherpa_jacket_brown",
    category: "jacket",
    colour: "brown",
    size: "L",
    length: "long",
    img: "./images/jackets/hm_sherpa_jacket_brown.png",
  },
  {
    id: 6,
    title: "levis_denim_jacket_blue",
    category: "jacket",
    colour: "blue",
    size: "L",
    length: "long",
    img: "./images/jackets/levis_denim_jacket_blue.png",
  },
  {
    id: 7,
    title: "levis_sherpa_jacket_black",
    category: "jacket",
    colour: "black",
    size: "XL",
    length: "long",
    img: "./images/jackets/levis_sherpa_jacket_black.png",
  },
  {
    id: 8,
    title: "redhead_jacket_grey",
    category: "jacket",
    colour: "grey",
    size: "xl",
    length: "long",
    img: "./images/jackets/redhead_jacket_grey.png",
  },
  {
    id: 9,
    title: "vans_denim_jacket_blue",
    category: "jacket",
    colour: "blue",
    size: "L",
    length: "long",
    img: "./images/jackets/vans_denim_jacket_blue.png",
  },
  {
    id: 10,
    title: "zara_denim_jacket_black",
    category: "jacket",
    colour: "black",
    size: "L",
    length: "long",
    img: "./images/jackets/zara_denim_jacket_black.png",
  },
  {
    id: 11,
    title: "ae_shirt_aloha",
    category: "tops",
    colour: "aloha",
    size: "L",
    length: "short",
    img: "./images/tops/ae_shirt_aloha.png",
  },
  {
    id: 12,
    title: "carhartt_long_tshirt_dark_grey",
    category: "tops",
    colour: "grey",
    size: "XL",
    length: "long",
    img: "./images/tops/carhartt_long_tshirt_dark_grey.png",
  },
  {
    id: 13,
    title: "carhartt_tshirt_black",
    category: "tops",
    colour: "grey",
    size: "XL",
    length: "short",
    img: "./images/tops/carhartt_tshirt_black.png",
  },
  {
    id: 14,
    title: "champion_long_tshirt_green",
    category: "tops",
    colour: "green",
    size: "L",
    length: "long",
    img: "./images/tops/champion_long_tshirt_green.png",
  },
  {
    id: 15,
    title: "champion_sweater_grey",
    category: "tops",
    colour: "grey",
    size: "XL",
    length: "long",
    img: "./images/tops/champion_sweater_grey.png",
  },
  {
    id: 16,
    title: "champion_tshirt_white",
    category: "tops",
    colour: "white",
    size: "L",
    length: "long",
    img: "./images/tops/champion_tshirt_white.png",
  },
  {
    id: 17,
    title: "ck_shirt_white",
    category: "tops",
    colour: "white",
    size: "L",
    length: "short",
    img: "./images/tops/ck_shirt_white.png",
  },
  {
    id: 18,
    title: "gap_sweater_camo",
    category: "tops",
    colour: "camo",
    size: "L",
    length: "long",
    img: "./images/tops/gap_sweater_camo.png",
  },
  {
    id: 19,
    title: "hm_shirt_keith_haring",
    category: "tops",
    colour: "aloha",
    size: "XL",
    length: "short",
    img: "./images/tops/hm_shirt_keith_haring.png",
  },
  {
    id: 20,
    title: "jordan_tshirt_shite",
    category: "tops",
    colour: "white",
    size: "L",
    length: "long",
    img: "./images/tops/jordan_tshirt_shite.png",
  },
  {
    id: 21,
    title: "levis_sweater_light_brown",
    category: "tops",
    colour: "brown",
    size: "XL",
    length: "long",
    img: "./images/tops/levis_sweater_light_brown.png",
  },
  {
    id: 22,
    title: "levis_tshirt_black",
    category: "tops",
    colour: "black",
    size: "XL",
    length: "short",
    img: "./images/tops/levis_tshirt_black.png",
  },
  {
    id: 23,
    title: "levis_tshirt_white",
    category: "tops",
    colour: "white",
    size: "XL",
    length: "short",
    img: "./images/tops/levis_tshirt_white.png",
  },
  {
    id: 24,
    title: "nike_sweater_sienna",
    category: "tops",
    colour: "sienna",
    size: "L",
    length: "long",
    img: "./images/tops/nike_sweater_sienna.png",
  },
  {
    id: 25,
    title: "nike_sweater_yellow",
    category: "tops",
    colour: "yellow",
    size: "XL",
    length: "long",
    img: "./images/tops/nike_sweater_yellow.png",
  },
  {
    id: 26,
    title: "posty_tshirt_black",
    category: "tops",
    colour: "black",
    size: "XL",
    length: "long",
    img: "./images/tops/posty_tshirt_black.png",
  },
  {
    id: 27,
    title: "pure_stuff_shirt_brown",
    category: "tops",
    colour: "brown",
    size: "XL",
    length: "long",
    img: "./images/tops/pure_stuff_shirt_brown.png",
  },
  {
    id: 28,
    title: "shirt_navy",
    category: "tops",
    colour: "navy",
    size: "L",
    length: "short",
    img: "./images/tops/shirt_navy.png",
  },
  {
    id: 29,
    title: "tshirt_white",
    category: "tops",
    colour: "white",
    size: "L",
    length: "short",
    img: "./images/tops/tshirt_white.png",
  },
  {
    id: 30,
    title: "zanerobe_shirt_black",
    category: "tops",
    colour: "black",
    size: "M",
    length: "long",
    img: "./images/tops/zanerobe_shirt_black.png",
  },
  {
    id: 31,
    title: "zara_shirt_yellow",
    category: "tops",
    colour: "yellow",
    size: "L",
    length: "long",
    img: "./images/tops/zara_shirt_yellow.png",
  },
  {
    id: 32,
    title: "zara_tshirt_white",
    category: "tops",
    colour: "white",
    size: "XL",
    length: "short",
    img: "./images/tops/zara_tshirt_white.png",
  },
  {
    id: 33,
    title: "ae_jeans_dark_blue",
    category: "bottoms",
    colour: "blue",
    size: "L",
    length: "long",
    img: "./images/bottoms/ae_jeans_dark_blue.png",
  },
  {
    id: 34,
    title: "ae_jeans_light_blue",
    category: "bottoms",
    colour: "blue",
    size: "L",
    length: "long",
    img: "./images/bottoms/ae_jeans_light_blue.png",
  },
  {
    id: 35,
    title: "gap_pants_beige",
    category: "bottoms",
    colour: "beige",
    size: "L",
    length: "long",
    img: "./images/bottoms/gap_pants_beige.png",
  },
 
  {
    id: 37,
    title: "levis_jeans_dark_blue",
    category: "bottoms",
    colour: "blue",
    size: "L",
    length: "long",
    img: "./images/bottoms/levis_jeans_dark_blue.png",
  },
  {
    id: 38,
    title: "levis_shorts_beige",
    category: "bottoms",
    colour: "beige",
    size: "L",
    length: "short",
    img: "./images/bottoms/levis_shorts_beige.png",
  },
  {
    id: 39,
    title: "nike_sweats_black",
    category: "bottoms",
    colour: "black",
    size: "L",
    length: "long",
    img: "./images/bottoms/nike_sweats_black.png",
  },
  {
    id: 40,
    title: "nike_swimwear_bw",
    category: "bottoms",
    colour: "white",
    size: "M",
    length: "short",
    img: "./images/bottoms/nike_swimwear_bw.png",
  },
  {
    id: 41,
    title: "shorts_beige",
    category: "bottoms",
    colour: "beige",
    size: "L",
    length: "short",
    img: "./images/bottoms/shorts_beige.png",
  },
  {
    id: 42,
    title: "shorts_camo",
    category: "bottoms",
    colour: "camo",
    size: "L",
    length: "short",
    img: "./images/bottoms/shorts_camo.png",
  },
  {
    id: 43,
    title: "shorts_dark_blue",
    category: "bottoms",
    colour: "blue",
    size: "L",
    length: "short",
    img: "./images/bottoms/shorts_dark_blue.png",
  },
  {
    id: 44,
    title: "shorts_grey",
    category: "bottoms",
    colour: "grey",
    size: "M",
    length: "short",
    img: "./images/bottoms/shorts_grey.png",
  },
  {
    id: 45,
    title: "shorts_navy",
    category: "bottoms",
    colour: "navy",
    size: "L",
    length: "short",
    img: "./images/bottoms/shorts_navy.png",
  },
  {
    id: 46,
    title: "bulls_hat_green",
    category: "hats",
    colour: "green",
    img: "./images/hats/bulls_hat_green.png",
  },
  {
    id: 47,
    title: "hat_black_brown",
    category: "hats",
    colour: "black",
    img: "./images/hats/hat_black_brown.png",
  },
  {
    id: 48,
    title: "hat_grey",
    category: "hats",
    colour: "grey",
    img: "./images/hats/hat_grey.png",
  },
  {
    id: 49,
    title: "levis_bucket_hat_black",
    category: "hats",
    colour: "black",
    img: "./images/hats/levis_bucket_hat_black.png",
  },
  {
    id: 50,
    title: "north_face_tuque_black",
    category: "hats",
    colour: "black",
    img: "./images/hats/north_face_tuque_black.png",
  },
  {
    id: 51,
    title: "snoopy_bucket_hat_yellow",
    category: "hats",
    colour: "yellow",
    img: "./images/hats/snoopy_bucket_hat_yellow.png",
  },
  {
    id: 52,
    title: "soopy_bucket_hat_white",
    category: "hats",
    colour: "white",
    img: "./images/hats/soopy_bucket_hat_white.png",
  },
  {
    id: 53,
    title: "nike_shoes_brown",
    category: "shoes",
    colour: "brown",
    img: "./images/shoes/nike_shoes_brown.png",
  },
  {
    id: 53,
    title: "nike_shoes_red",
    category: "shoes",
    colour: "red",
    img: "./images/shoes/nike_shoes_red.png",
  },
  {
    id: 53,
    title: "stan_shoes_white",
    category: "shoes",
    colour: "white",
    img: "./images/shoes/stan_shoes_white.png",
  },
  {
    id: 53,
    title: "timber_shoes_black",
    category: "shoes",
    colour: "black",
    img: "./images/shoes/timber_shoes_black.png",
  },
  {
    id: 53,
    title: "vans_shoes_black",
    category: "shoes",
    colour: "black",
    img: "./images/shoes/vans_shoes_black.png",
  },

];

export const mannequins =[
    {
      id: 1,
      img: "./images/mannequins/upper_body.PNG",
    },
    {
      id: 2,
      img: "./images/mannequins/lower_body.PNG",
    }
  ]
